### ISSUE TITLE
Changing the audio settings can make the output frequency desync

### ISSUE THREAD

**Issue by NieDzejkob** [higan-emu/higan#13]
Steps to reproduce:
1. Load a game. I have used a Game Boy Color one, but I doubt that the system matters.
2. In the audio settings, choose the "PulseAudio Simple" driver.
3. Click "Change".
4. Change the frequency from the default 48000 to 96000.
5. Choose the "ALSA" driver.
6. Click "Change". The frequency dropdown will be grayed out and forced to 48000. (on my system, the sound doesn't play at all in this moment. Probably some compatibility problem)
7. Choose "PulseAudio Simple" again and click "Change". The frequency dropdown is no longer gray, but it still shows 48000.

Now the game plays at half the speed. The FPS counter shows 30, the pitch and music tempo is lower.

**Comment by Screwtapello** [comment]
I followed your reproduction steps with the latest nightly, but the problem didn't occur for me. There have been fixes for ALSA, PulseAudio and PulseAudio-Simple since this issue was filed, it's possible it has been accidentally fixed.

Please test the latest nightly, and leave a comment if you can still reproduce the problem, so it can be looked into further.
