### ISSUE TITLE
Fast-forward doesn't work

### ISSUE THREAD

**Issue by NieDzejkob** [higan-emu/higan#14]
I have bound the `F` key to the "fast-forward" option. I'm using the OpenGL 3.2 video driver, PulseAudio Simple audio driver, and SDL input driver, testing on the Game Boy Color in the GTK GUI. When I hold F, nothing happens - the FPS stays at a steady 60. I don't think it's a performance problem, since when I choose a different audio backend, the sync seems to break and the FPS hovers around 75 FPS.

**Comment by Screwtapello** [comment]
The "Fast Forward" option works by temporarily disabling the "Blocking" option for both the audio and video drivers (in previous versions of higan, those options were labelled "Synchronize"), which means audio and video should play back as fast as possible, instead of being limited to a sensible speed.

Unfortunately, the documentation for the PulseAudio Simple API [says](https://www.freedesktop.org/software/pulseaudio/doxygen/simple.html#transfer_sec) "Note that these operations always block." higan cannot disable "Blocking" for the PulseAudio Simple driver, because that's not possible. Therefore, fast-forwarding is not possible when that driver is active.

As far as I know, the PulseAudio driver should work just as well as the PulseAudio Simple driver, and it has a few extra features (like fast forward support, and at least an attempt at dynamic rate control) so that's almost certainly the one you want to use. If the PulseAudio driver doesn't work for you, please file a new issue about that.
