### ISSUE TITLE
144Hz?

### ISSUE THREAD

**Issue by drpaneas** [higan-emu/higan#147]
I am playing SNES on my gaming monitor that's up to 144Hz. However no matter what settings I've tried, the game always plays at 60 FPS.

**Comment by jchv** [comment]
The Super Nintendo/Super Famicom have a pixel process unit that outputs a frame at a rate of roughly 60 hz (NTSC) or 50 hz (PAL). Games are designed around this, so they will not run at higher framerates than that.

Some emulators can use high refresh rate monitors to improve visual clarity by using techniques like Black Frame Insertion. This doesn't increase the framerate of the game but can reduce ghosting artifacts of motion on screen. [Example](https://www.testufo.com/blackframes). (Warning: do not view this animation if you are prone to epileptic seizures.)

Otherwise, though, a high refresh rate monitor does not offer much for retro gaming. Most retro consoles and games for them are designed in such a way that it's impossible to get higher framerates.
