### ISSUE TITLE
Include quark shaders and default configuration files in the higan-emu repository and in nightly builds

### ISSUE THREAD

**Issue by byuu** [higan-emu/higan#2]
The bsnes-emu project has a shaders folder that contains various quark-format pixel shaders. We should include this folder in higan-emu, and then also ensure that the shaders are bundled into both nightly builds (after issue #1 is resolved.)

Note that byuu is vastly more capable of using these pixel shaders on account of including scanline-based renderers that can output screen images in lower resolutions, which is a requirement for most of them to work well.

The byuu emulator should also ship with the settings.bml file from the official Windows v4 release, so that controls and hotkeys are configured out of the box. It would probably be nice to create a more complete higan default configuration state as well, but seeing as that is substantially more work, I think it's okay to not worry about that for now.

**Comment by Screwtapello** [comment]
A question of policy for my fellow maintainers: currently the shaders in the byuu v4 release are a hand-picked subset of the ones provided in https://github.com/hizzlekizzle/quark-shaders (the prettiest ones, I think). Do we want to:

- straight up add hunterk's quark-shaders repo as a Git submodule, and ship every available shader without bothering to pick any
    - easy to do, easy to keep up-to-date
    - we ship a lot of shaders that may not work terribly well in higan, or be redundant
- add hunterk's quark-shaders repo as a Git subtree, so we can apply local changes to shaders (deleting the ones we don't want) without losing the ability to merge upstream changes
    - more work to keep up-to-date
    - more control over what we ship
    - can we be bothered to exercise that control?
- Just copy the existing bsnes shaders into the higan repo, obscuring the source and letting them drift out-of-date
    - very easy to do
    - probably won't drift out of date *too* quickly?
- Not include any shaders, and WONTFIX this issue
    - very, very easy to do
    - users miss out on a lot of great shaders

Bonus round: Do we want to have a separate bunch of shaders for higan (because its dot-renderers always render at high resolution) versus byuu/bsnes (scanline renderers that work nicely with traditional shaders)?

Also tagging @hizzlekizzle in case he has an opinion.

**Comment by Screwtapello** [comment]
> The byuu emulator should also ship with the settings.bml file from the official Windows v4 release, so that controls and hotkeys are configured out of the box.

The `settings.bml` from the official Windows v4 release includes Windows-specific drivers. Using it as-is on Linux causes the "Audio" and "Input" drivers to default to None, which seems a bad idea. On the other hand, I can just delete those settings, leaving behind the controls and hotkeys, and I'll get the default drivers for the current platform - but were those drivers set for a reason? Will Windows users have sucky default drivers if we ship a partial `settings.bml`?

**Comment by hizzlekizzle** [comment]
Subtree seems like the best move to me. OTOH, they don't change all that often and they're easy enough to just delete and replace in the event of major changes, so just copying in the ones you want seems like a good choice, too.

**Comment by Screwtapello** [comment]
PR #45 should fix the "shaders" half of this issue. For simplicity's sake, I just went and subtree'd the whole repo rather than getting picky about which shaders to include.
