### ISSUE TITLE
byuu: Clarify the virtual gamepad layout

### ISSUE THREAD

**Issue by jbo-85** [higan-emu/higan#81]
the keyboard mappings in byuu are swapped
a is swapped with b, x is swapped with y
I tested that with the controller test in the snes test program, but it's not limited to the SNES

**Comment by Screwtapello** [comment]
Since byuu is a multi-system emulator, not just a SNES emulator, it asks the user to map their controller to a "generic gamepad", and there are internal mappings from the generic gamepad to each supported system. The generic gamepad's buttons are labelled according to the Xbox scheme, so this is technically Not A Bug.

I agree it's confusing, though. Perhaps instead of giving specific labels for the face buttons, it should say something like Upper Face/Right Face/Lower Face/Left Face? Or "Action" instead of "Face"? Or try to use the PlayStation glyphs instead?

**Comment by asuramaru** [comment]
On this note, we're missing bindings for buttons like L2/R2 for the Sony Playstation. It gets even worse when you factor in the DualShock's additional thumb stick and the buttons behind them. The current system also limits us to only one player, and won't support mice and light guns. The virtual gamepad implementation feels half-baked and needs a rethink.

**Comment by jbo-85** [comment]
> Since byuu is a multi-system emulator, not just a SNES emulator, it asks the user to map their controller to a "generic gamepad", and there are internal mappings from the generic gamepad to each supported system. The generic gamepad's buttons are labelled according to the Xbox scheme, so this is technically Not A Bug.
Ok, then the problem is that the internal mappings for those buttons are incorrect for the SNES/GBA at least.

**Comment by Kawa-oneechan** [comment]
For what it's worth, last time I played a SNES game on an emulator and bothered to use my gamepad I just ignored the fact that the letters and colors were wrong. I'm a touch typist after all, why not use a gamepad on touch? You wouldn't have the time to look at your hands anyway, the average video game goes a little faster than a word processor.

So yeah, maybe I'm misunderstanding the problem here, but I don't really *see* the problem.

**Comment by jbo-85** [comment]
I'm using a keyboard, not a gamepad
I just swapped the input bindings myself

> For what it's worth, last time I played a SNES game on an emulator and bothered to use my gamepad I just ignored the fact that the letters and colors were wrong. I'm a touch typist after all, why not use a gamepad on touch?

Without knowing what scheme the input dialog is using you kinda have to guess, which button is which, when your using a non-xbox gamepad or a keyboard

Right now you kinda have to look at the source code to find the real mappings and that is really "s......uboptimal"
Just look at the mega drive (byuu/emulator/mega-drive.cpp)
ABCXYZ are mapped to XABYLR on the xbox controller scheme, how are you supposed to know that without looking at the source code?

ways around that
* allow to map the virtual gamepad to each system, instead of hardcoding it
* add some schematics for the various gamepads (at least for the xbox-controller)

**Comment by asuramaru** [comment]
The most sensible path forward I see is to move the classic higan (v106) style input mapping system back to this GUI.
Perhaps we could have some other window or button that can auto-map a detected Xbox controller to one or all systems.
Any changes to the input mapping seems to be a massive undertaking and I'm not sure any of us even know how to do it, so we're going to need a volunteer. And on that point, **not it.**

**Comment by FitzRoyX** [comment]
I feel like my proposed solution to this was good, but byuu didn't take it.

![cfgb](https://user-images.githubusercontent.com/57089001/90805642-8380d980-e2e1-11ea-8085-9a98171e5476.png)

**Comment by Kawa-oneechan** [comment]
I like the triple label thing.

**Comment by Screwtapello** [comment]
byuu-ui is in part a reaction to the crippling complexity of higan-ui. A good part of that comes from wanting to support every kind of PC controller mapped to every possible emulated controller, which is admirable but the complexity quickly gets overwhelming. byuu-ui's solution is to say "most people will be playing with a modern four-face-button gamepad, so that's the only controller we'll support", which is surprisingly workable. It's certainly not *perfect*, but it's a great 80%-solution-for-20%-effort idea.

There's a lot of scope for making byuu-ui's input handling more comprehensive, supporting different input controllers, and customising the mapping to emulated controllers, but I think Simplicity is a core value of byuu-ui. People who want to customise exactly how the controller mapping works can use higan-ui.

As such, I think there's two things we need to do here:

- Update the UI to make the layout of the virtual gamepad clearer, by listing all the popular conventions ("X/Y/△") or by using clearer labels ("Upper Face Button")
- Make sure there's documentation that describes the layout, and how those buttons get mapped to emulated controllers

**Comment by Screwtapello** [comment]
Actually, one to-do item per issue. I split off the documentation into #83, this issue is now all about updating the UI to make the layout of the virtual gamepad clearer.

**Comment by FitzRoyX** [comment]
So I just compiled this for the first time in a while and noticed that N64 labels were added to the "global pad", which... doesn't make any sense to me. We're supposed to be targetting modern pads for the labels... So there should instead be bindings for left and right thumbstick, as well as L2 and R2. My googling indicates that most people just bind the N64 C-buttons to the right thumbstick.

I think I can create a PR for this if you agree.
