### ISSUE TITLE
CGB: Sprite palette incorrect in Pokemon Crystal

### ISSUE THREAD

**Issue by Screwtapello** [higan-emu/higan#85]
When playing Pokemon Crystal, the player sprite (and other character sprites walking around the map) appear in a random palette that changes as you move from room to room, or visit different menus. Here the player should have a black outline, instead of being a red blob:

![higan-ui 2020-08-22 19-02-35](https://user-images.githubusercontent.com/1450918/90952887-6f3c0880-e4aa-11ea-86ac-3c37dbb6a4ac.png)

This doesn't appear on FitzRoy's game bug list in #47, so it may be a regression. We should pin that down.

**Comment by asuramaru** [comment]
Here is the fix for this bug:

https://github.com/higan-emu/higan/blob/master/higan/gb/ppu/io.cpp#L70

Notice how the OBP0 read accesses obp[0-3][0-3], but the OBP1 read accesses obp[1][0-3]. obp is declared as obp[2][4]. We need to change the OBP0 read to obp[0][0-3] and this bug goes away.

Another problem is with Pokemon Crystal save files, which are 64KB.

https://github.com/higan-emu/higan/blob/master/icarus/cartridge/game-boy.cpp#L243

We need to support 128KB and 64KB cases as per https://gbdev.gg8.se/wiki/articles/The_Cartridge_Header#0149_-_RAM_Size by adding:

case 0x04: ramSize = 128*1024 break;
case 0x05: ramSize = 64*1024; break;

And then we have to update the MBC3 mapper to be able to use all 64KB.

https://github.com/higan-emu/higan/blob/master/higan/gb/cartridge/mbc3/mbc3.cpp#L28

https://github.com/higan-emu/higan/blob/master/higan/gb/cartridge/mbc3/mbc3.cpp#L71

We do this by changing if(io.ram.bank <=3) to if(io.ram.bank <= 7)

If someone else wants to submit a pull request, please feel free to do so, no credit is necessary.

The realtime clock is still broken. Seems to be beyond my abilities to determine why. But at least with these patches the game is now playable.

**Comment by Screwtapello** [comment]
The sprite palette problem is fixed, so this issue is closed. However, Pokémon Crystal still seems to be missing RTC support (#99) and Pocket Monsters Crystal specifically needs mapper support (#98).
